name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2022

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: jruby-9.3, value: jruby-9.3.9.0 }
          - { name: ruby-2.7, value: 2.7.7 }
          - { name: ruby-3.0, value: 3.0.5 }
          - { name: ruby-3.1, value: 3.1.3 }

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Setup ruby
        uses: ruby/setup-ruby@4b2d1d631efa087f8896c15a0c6023dc2f483198 # v1.128.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Setup java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: temurin
          java-version: 18.0.0
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
        shell: bash
        if: "!startsWith(matrix.ruby.name, 'jruby')"
